### ISSUE TITLE
UI url for Negative News Screening

### ISSUE THREAD

**Issue by seansund** [ibm-ecosystem-engineering/watsonx-demo-ui#11]

**Comment by sayantaun** [comment]
Github - https://github.com/sayantaun/Watsonx-demo-neg-news-ey/tree/main

UI URL to be submitted after code engine deploy. (eyibmsbox cloud account)

ETA-6th Sept 2023

**Comment by sayantaun** [comment]
https://negnews.161ia4n12g8f.us-south.codeengine.appdomain.cloud/
