### ISSUE TITLE
Provide Customer Risk Assessment API specification

### ISSUE THREAD

**Issue by seansund** [ibm-ecosystem-engineering/watsonx-demo-ui#2]
Need the following information for the Customer Risk Assessment API that is part of the KYC Case Workflow:

- Endpoint url
- Input/output schema
- Error handling

**Comment by seansund** [comment]
https://ibm.box.com/s/04am8biv38ctzdkxpbb19ciwpusguedu

**Comment by saratrip** [comment]
We have deployed the KYC RISK SCORE in EY Cloud.  Ready for Testing..
URL for Risk Assessment engine invocation.===================
https://cpd-cp4ba.cp4ba-cra-c6c44da74def18a795b07cc32856e138-0000.us-south.containers.appdomain.cloud/ae-pbk/Risk%20Assessment%20Business%20Application(EKYCBA)
username: cp4admin
password: q5j1wRnRf4FrumkbFs76
URL for RiskAccessment Studio ===============
https://cpd-cp4ba.cp4ba-cra-c6c44da74def18a795b07cc32856e138-0000.us-south.containers.appdomain.cloud/
 username: cp4admin
 password: q5j1wRnRf4FrumkbFs76 (edited)
